//! The About & licenses screen: the build version, punktfunk's own licence, and the
//! generated third-party notices, as one scrollable wall of text. The card chrome is
//! drawn here; the document body is its own scroll-content tile, composited separately.
//! Logic lives in `app::state::about`.
//!
//! **Scrolling is hardware-accelerated, the same way the Settings modal's row list is.**
//! `THIRD-PARTY-NOTICES.txt` wraps to ~12,000 visual lines, far too tall to bake into one
//! GPU texture, so About needs a *windowed* content tile where Settings' 9 rows fit in
//! one. [`wrap_document`] wraps the document once, up front, into a flat list of visual
//! lines with a uniform stride — the unit `ui::scroll::ScrollWindow`/`ui::scroll::ContentWindow` scroll
//! over — and [`draw_window`] rasterizes only a bounded slice at a time (uncached; see
//! `ui::draw_text_uncached`). Scrolling within that slice is a pure `DrawCmd::TexCropped`.
use crate::core::VERSION;

pub const TITLE: &str = "About & licenses";

pub fn subtitle() -> String {
    format!("Version {VERSION}")
}

/// punktfunk-webos' own licence, both halves of the `MIT OR Apache-2.0` dual grant.
const APP_LICENSE: &str = concat!(
    include_str!("../../../LICENSE-MIT"),
    "\n\n=============================== Apache-2.0 ===============================\n\n",
    include_str!("../../../LICENSE-APACHE"),
);

/// Third-party notices for every crate that links on the webOS target, plus the
/// bundled non-Rust components. Generated by `build.rs` during compilation — regenerate
/// (via `task notices`) whenever the dependency tree changes.
const THIRD_PARTY_NOTICES: &str = include_str!("../../../THIRD-PARTY-NOTICES.txt");

/// The whole document, as one static line list. `include_str!` gives a `&'static str`,
/// so splitting it costs one `Vec` of string slices — no copying of the ~560 KB body.
pub fn lines() -> Vec<&'static str> {
    let mut out = vec![
        "punktfunk for webOS",
        "",
        "A native LG webOS TV client for punktfunk — low-latency desktop and",
        "game streaming. Built on the upstream punktfunk project; all credit for",
        "the protocol, FEC/crypto core, and host implementation belongs there.",
        "",
        "  https://github.com/punktfunk/client-webos",
        "  https://git.unom.io/unom/punktfunk",
        "",
        "Licensed under MIT OR Apache-2.0, at your option.",
        "",
        "========================================================================",
        "PUNKTFUNK-WEBOS LICENCE",
        "========================================================================",
        "",
    ];
    out.extend(APP_LICENSE.lines());
    out.push("");
    out.extend(THIRD_PARTY_NOTICES.lines());
    out
}
